-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 16:38:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema construction_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `construction_db` ;

-- -----------------------------------------------------
-- Schema construction_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `construction_db` DEFAULT CHARACTER SET utf8 ;
USE `construction_db` ;

-- -----------------------------------------------------
-- Table `construction_db`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`area` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`category` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `construction_db`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`client` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `project_category_id` INT NULL,
  `project_id` INT NULL,
  `mobile_no` VARCHAR(15) NULL,
  `address` TEXT NULL,
  `gst` VARCHAR(100) NULL,
  `pan` VARCHAR(45) NULL,
  `adhar_no` VARCHAR(45) NULL,
  `date_of_birth` DATETIME NULL,
  `city_id` INT NULL,
  `area` TEXT NULL,
  `acc_holder_name` VARCHAR(255) NULL,
  `branch_name` VARCHAR(100) NULL,
  `ifsc` VARCHAR(45) NULL,
  `bank_name` VARCHAR(255) NULL,
  `remark` TEXT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`company` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `cin_no` VARCHAR(45) NULL,
  `gst_no` VARCHAR(45) NULL,
  `logo_url` TEXT NULL,
  `address` TEXT NULL,
  `mobile_no` VARCHAR(15) NULL,
  `email` VARCHAR(255) NULL,
  `is_active` BIT(1) NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`company_fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`company_fund` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`company_fund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  `remark` TEXT NOT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`distribute_fund`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`distribute_fund` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`distribute_fund` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `distribute_fund` DECIMAL NOT NULL,
  `transaction_type` VARCHAR(45) NOT NULL,
  `remark` TEXT NOT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`employee` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `gender` TEXT NULL,
  `father_name` VARCHAR(255) NULL,
  `mother_name` VARCHAR(255) NULL,
  `husband_name` VARCHAR(255) NULL,
  `date_of_birth` DATETIME NULL,
  `nationality_id` INT NULL,
  `state` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `address` TEXT NULL,
  `mobile_no` VARCHAR(15) NULL,
  `alternate_mobile_no` VARCHAR(15) NULL,
  `pan` VARCHAR(45) NULL,
  `image` VARCHAR(255) NULL,
  `email` VARCHAR(45) NULL,
  `department` TEXT NULL,
  `employee_term` TEXT NULL,
  `monthly_salary` DECIMAL NULL,
  `designation` VARCHAR(45) NULL,
  `joining_date_of_duty` DATETIME NULL,
  `paid_leave` INT NULL,
  `id_card_no` VARCHAR(45) NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`expense`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`expense` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`expense` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `construction_db`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`inventory` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`inventory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `hsn` INT NULL,
  `description` TEXT NULL,
  `opening_stock` DECIMAL NULL,
  `purchase_rate` DECIMAL NULL,
  `sales_rate` DECIMAL NULL,
  `mrp` DECIMAL NULL,
  `cgst` DECIMAL NULL,
  `sgst` DECIMAL NULL,
  `igst` DECIMAL NULL,
  `unit_id` INT NULL,
  `status_id` INT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`partner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`partner` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`partner` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `mobile_no` VARCHAR(15) NULL,
  `city` VARCHAR(45) NULL,
  `address` TEXT NULL,
  `acc_no` VARCHAR(50) NULL,
  `branch` VARCHAR(50) NULL,
  `ifsc_code` VARCHAR(50) NULL,
  `gstn_no` VARCHAR(100) NULL,
  `status` BIT(1) NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`project` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`project` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `category_id` INT NULL,
  `sub_contractor_name` VARCHAR(255) NULL,
  `sub_contractor_id` INT NULL,
  `description` TEXT NULL,
  `tender_amount` DECIMAL NULL,
  `below_amount` DECIMAL NULL,
  `department` VARCHAR(255) NULL,
  `budget` DECIMAL NULL,
  `completion_date` DATETIME NULL,
  `performance_security_deposit` DECIMAL NULL,
  `security_deposit` DECIMAL NULL,
  `city_id` INT NULL,
  `area` TEXT NULL,
  `maintenace_date` DECIMAL NULL,
  `partner_id` INT NULL,
  `date_of_work_order` DECIMAL NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`ra_bill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`ra_bill` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`ra_bill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `payment_from` VARCHAR(255) NOT NULL,
  `project_id` INT NULL,
  `payment_mode` VARCHAR(45) NULL,
  `transaction_no` INT NULL,
  `bank_name` VARCHAR(255) NULL,
  `bill_amount` DECIMAL NULL,
  `ra_number` INT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`security_deposit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`security_deposit` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`security_deposit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `project_name` VARCHAR(255) NULL,
  `maturity_date` DATETIME NULL,
  `amount` DECIMAL NULL,
  `dd_tdr_date` DATETIME NULL,
  `department` VARCHAR(255) NULL,
  `payment_type` VARCHAR(45) NULL COMMENT 'DD / TDR / BG',
  `tdr_no` VARCHAR(255) NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`sub_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`sub_category` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`sub_category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `category_id` INT NOT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `construction_db`.`sub_contractor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`sub_contractor` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`sub_contractor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `mob_no` VARCHAR(15) NULL,
  `alternate_mob_no` VARCHAR(15) NULL,
  `address` TEXT NULL,
  `branch` VARCHAR(50) NULL,
  `ifsc` VARCHAR(50) NULL,
  `acc_no` VARCHAR(100) NULL,
  `pan` VARCHAR(50) NULL,
  `status` BIT(1) NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`tax`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`tax` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`tax` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `cgst` DECIMAL NULL,
  `igst` DECIMAL NULL,
  `sgst` DECIMAL NULL,
  `cess` DECIMAL NULL,
  `other_tax` DECIMAL NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`unit` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`unit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `company_id` INT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `construction_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`user` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `user_type` VARCHAR(45) NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `mobile_no` VARCHAR(15) NULL,
  `pan` VARCHAR(45) NULL,
  `adhar` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `date_of_birth` DATETIME NULL,
  `address` TEXT NULL,
  `pincode` INT NULL,
  `city_id` INT NULL,
  `area` TEXT NULL,
  `master` TEXT NULL,
  `system_user` TEXT NULL,
  `salary` TEXT NULL,
  `home_resource` TEXT NULL,
  `clients` TEXT NULL,
  `expenses` TEXT NULL,
  `employee` TEXT NULL,
  `employee_transaction` TEXT NULL,
  `to_do_list` TEXT NULL,
  `sale` TEXT NULL,
  `tender` TEXT NULL,
  `vehicle_information` TEXT NULL,
  `labour` TEXT NULL,
  `investment` TEXT NULL,
  `sales_and_purchse` TEXT NULL,
  `vender` TEXT NULL,
  `security_deposite` TEXT NULL,
  `transaction` TEXT NULL,
  `tax_invoice` TEXT NULL,
  `interest` TEXT NULL,
  `asset` TEXT NULL,
  `tenant` TEXT NULL,
  `bill_purchase` TEXT NULL,
  `payment` TEXT NULL,
  `insurance_policy` TEXT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`vendor` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `business_name` VARCHAR(255) NULL,
  `opening_bal` DECIMAL NULL,
  `op_bal_type` VARCHAR(45) NULL,
  `cin_no` VARCHAR(100) NULL,
  `pan` VARCHAR(45) NULL,
  `gst` VARCHAR(100) NULL,
  `mobile_no` VARCHAR(15) NULL,
  `email` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `pincode` INT NULL,
  `city_id` INT NULL,
  `upi` VARCHAR(255) NULL,
  `area` TEXT NULL,
  `acc_holder_name` VARCHAR(255) NULL,
  `acc_no` VARCHAR(255) NULL,
  `branch_name` VARCHAR(100) NULL,
  `ifsc` VARCHAR(45) NULL,
  `bank_name` VARCHAR(255) NULL,
  `remark` TEXT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `construction_db`.`vendor_purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `construction_db`.`vendor_purchase` ;

CREATE TABLE IF NOT EXISTS `construction_db`.`vendor_purchase` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `transaction_date` DATETIME NOT NULL,
  `company_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  `transaction_no` VARCHAR(100) NULL,
  `payment_type` VARCHAR(45) NULL,
  `payment_amount` DECIMAL NULL,
  `remark` TEXT NULL,
  `vendor_no` VARCHAR(100) NULL,
  `gst` VARCHAR(100) NULL,
  `bal` DECIMAL NULL,
  `mobile_no` VARCHAR(15) NULL,
  `email` VARCHAR(255) NULL,
  `address` TEXT NULL,
  `state` TEXT NULL,
  `is_active` BIT(1) NULL,
  `created_by` VARCHAR(255) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_by` VARCHAR(255) NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
